#!/bin/bash
set -e
PATH=/tmp/vendor/bin:$PATH

cmd="phing"

if [ -n "$ACTION_QUIET" ]
then
    cmd="$cmd -quiet"
fi

if [ -n "$ACTION_SILENT" ]
then
    cmd="$cmd -silent"
fi

if [ -n "$ACTION_VERBOSE" ]
then
    cmd="$cmd -verbose"
fi

if [ -n "$ACTION_DEBUG" ]
then
    cmd="$cmd -debug"
fi

if [ -n "$ACTION_EMACS" ]
then
    cmd="$cmd -emacs"
fi

if [ -n "$ACTION_LONGTARGETS" ]
then
    cmd="$cmd -longtargets"
fi

if [ -n "$ACTION_BUILDFILE" ]
then
    cmd="$cmd -f '$ACTION_BUILDFILE'"
fi

if [ -n "$ACTION_TARGETS" ]
then
    cmd="$cmd $ACTION_TARGETS"
fi

echo "Command: $cmd"
eval "$cmd"
