#!/bin/bash
set -e
PATH=/tmp/vendor/bin:$PATH

cmd="phing"

if [ -n "$action_buildfile" ]
then
				cmd="$cmd -f '$action_buildfile'"
fi

if [ -n "$action_targets" ]
then
				cmd="$cmd $action_targets"
fi

echo "Command: $cmd"
eval "$cmd"
